# Generated by Django 4.2.7 on 2024-01-22 18:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_card_id_alter_gamehistory_id_alter_gameroom_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='game_room',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='player',
            name='game_room',
        ),
        migrations.RemoveField(
            model_name='player',
            name='player',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='is_game_running',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='joined_player_count',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='type',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='unique_game_id',
        ),
        migrations.AddField(
            model_name='gameroom',
            name='room_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GameHistory',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.AddField(
            model_name='trackplayers',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gameroom'),
        ),
    ]
